version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - javascript
    rebase-strategy: auto
    versioning-strategy: increase
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      npm-runtime-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      npm-development-minor-and-patch:
        dependency-type: development
        exclude-patterns:
          - "@types/*"
        update-types:
          - minor
          - patch
      npm-types-minor-and-patch:
        patterns:
          - '@types/*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Asia/Seoul
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
    rebase-strategy: auto
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
